/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickergame;

import static clickergame.Records.info;
import static clickergame.Records.modelo;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Sierra
 */
public class clicker extends javax.swing.JFrame{

    /**
     * Creates new form clicker
     */
    public clicker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pbJugador1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pbJugador2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pbJugador3 = new javax.swing.JProgressBar();
        lblJugador = new javax.swing.JLabel();
        pbJugador4 = new javax.swing.JProgressBar();
        btnIniciar = new javax.swing.JButton();
        btnPresionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Lucida Fax", 3, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CLICKER GAME");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, -1));

        btnCrear.setText("Crear corredor");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        btn.setText("Historial");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Santiago");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(pbJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 360, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Miguel");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(pbJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 360, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Juan José");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(pbJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 360, 30));

        lblJugador.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setText("Player 4");
        getContentPane().add(lblJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        getContentPane().add(pbJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 360, 30));

        btnIniciar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnIniciar.setText("INICIAR");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 90, 30));

        btnPresionar.setBackground(new java.awt.Color(255, 0, 0));
        btnPresionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        btnPresionar.setBorderPainted(false);
        btnPresionar.setContentAreaFilled(false);
        btnPresionar.setEnabled(false);
        btnPresionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPresionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 80, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pst5.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 590, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clickkkk.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lblFondo.setBackground(new java.awt.Color(51, 51, 51));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresionarActionPerformed
        // TODO add your handling code here:
        x++;
        pbJugador4.setValue(x);
        
        if (x == 100)
        {
            if (pbJugador1.getValue() < 100 && pbJugador3.getValue() < 100 && pbJugador2.getValue() < 100)
            {
                double tiempo = Double.valueOf(pbJugador3.getValue());
                Jugadores j = new Jugadores(lblJugador.getText(),Double.toString(tiempo/5));
                Datos.add(j);
                try
                {
                    ObjectOutputStream escribirArchivo = new ObjectOutputStream(new FileOutputStream("records.car"));

                    escribirArchivo.writeObject(Datos);
                    escribirArchivo.close();

                }
                catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }
                JOptionPane.showMessageDialog(this, "Has ganado en " + Double.toString(tiempo/5) + " segundos" , "Ganador", JOptionPane.INFORMATION_MESSAGE); 
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Has perdido", "Perdedor", JOptionPane.INFORMATION_MESSAGE);
            }
            j1.Stop();
            j2.Stop();
            j3.Stop();
            x = 0;
            pbJugador1.setValue(x);
            pbJugador2.setValue(x);
            pbJugador3.setValue(x);
            pbJugador4.setValue(x);
            lblJugador.setText("Jugador 4");
            btnPresionar.setEnabled(false);
            btnCrear.setVisible(true);
        }
        
    }//GEN-LAST:event_btnPresionarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        j1 = new NPC("a", 250, pbJugador1);
        j2 = new NPC("b", 300, pbJugador2);
        j3 = new NPC("c", 200, pbJugador3);
        j1.start();
        j2.start();
        j3.start();
        btnIniciar.setEnabled(false);
        clicker.btnPresionar.setEnabled(true);
        btnCrear.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        Registro r = new Registro();
        r.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            ObjectInputStream leerArchivo = new ObjectInputStream(new FileInputStream("records.car"));
            
            Datos = (ArrayList<Jugadores>) leerArchivo.readObject();
            leerArchivo.close();
            /*for (int i = 0; i < listaJugadores.size(); i++)
            {
                info[0]=listaJugadores.get(i).getNombre();
                info[1]=listaJugadores.get(i).getTiempo();
                modelo.addRow(info);
            }*/
            
        }
        
        catch (Exception ex)
        {
           JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE); 
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        Records r = new Records();
        r.setVisible(true);
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clicker().setVisible(true);
            }
        });
    }

    int x = 0;
    NPC j1;
    NPC j2;
    NPC j3;
    static ArrayList<Jugadores> Datos = new ArrayList<Jugadores>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnCrear;
    public static javax.swing.JButton btnIniciar;
    public static javax.swing.JButton btnPresionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFondo;
    public static javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JProgressBar pbJugador1;
    private javax.swing.JProgressBar pbJugador2;
    private javax.swing.JProgressBar pbJugador3;
    private javax.swing.JProgressBar pbJugador4;
    // End of variables declaration//GEN-END:variables
}
