/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva_vuelos;
import java.util.ArrayList;
import javax.swing.JButton;


/**
 *
 * @author User
 */
public class Interfaz extends javax.swing.JFrame {
    
    
    /**
     * Creates new form 
     */
    public Interfaz() {
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        progreso = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Libres = new javax.swing.JTextField();
        Ocupados = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hombres = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mayores = new javax.swing.JTextField();
        menores = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        promEdad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        viejo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        joven = new javax.swing.JTextField();
        mujeres = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Reload = new javax.swing.JButton();
        Registrari = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Infoi = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
        b38 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b47 = new javax.swing.JButton();
        b48 = new javax.swing.JButton();
        b49 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        progress = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        jTextField10.setText("jTextField10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlHighlight);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Porcentaje:");
        jLabel1.setAlignmentX(0.2F);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        b1.setBackground(new java.awt.Color(255, 255, 0));
        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setText("1");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        b2.setBackground(new java.awt.Color(255, 255, 0));
        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText("2");
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        b3.setBackground(new java.awt.Color(255, 255, 0));
        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setText("3");
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        b4.setBackground(new java.awt.Color(255, 255, 0));
        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setText("4");
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        b5.setBackground(new java.awt.Color(255, 255, 0));
        b5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b5.setText("5");
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        b6.setBackground(new java.awt.Color(255, 255, 0));
        b6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b6.setText("6");
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        b7.setBackground(new java.awt.Color(255, 255, 0));
        b7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b7.setText("7");
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        b8.setBackground(new java.awt.Color(255, 255, 0));
        b8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b8.setText("8");
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        progreso.setMaximum(50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 20));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Puestos Libres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Puestos Ocupados:");

        Libres.setEditable(false);
        Libres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibresActionPerformed(evt);
            }
        });

        Ocupados.setEditable(false);
        Ocupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcupadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ocupados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Libres, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Libres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ocupados, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 140));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estadísticas:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ocupación por Sexo:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ocupación por mayor o menor de Edad:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hombre(s):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mujer(es):");

        hombres.setEditable(false);

        jTextField4.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mayor(es):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menor(es):");

        mayores.setEditable(false);

        menores.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Promedio de Edad:");

        promEdad.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre y Edad del más Joven:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre y Edad del más Mayor:");

        viejo.setEditable(false);

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("jLabel15");

        joven.setEditable(false);

        mujeres.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ocupación por Edad:");

        Reload.setBackground(new java.awt.Color(102, 102, 102));
        Reload.setForeground(new java.awt.Color(255, 255, 255));
        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(promEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(menores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(mujeres))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(hombres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel16))
                                .addGap(668, 668, 668)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1335, 1335, 1335)
                                        .addComponent(jTextField4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1059, 1059, 1059)
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(260, 260, 260)
                                        .addComponent(Reload)
                                        .addGap(124, 124, 124)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mayores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(706, 706, 706))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1683, 1683, 1683))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viejo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joven, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(hombres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(mujeres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mayores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(menores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(joven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Reload))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 380, 480));

        Registrari.setBackground(new java.awt.Color(153, 153, 255));
        Registrari.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Registrari.setText("Registrar Pasajero");
        Registrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrariActionPerformed(evt);
            }
        });
        getContentPane().add(Registrari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, -1, -1));

        Buscar.setBackground(new java.awt.Color(153, 153, 255));
        Buscar.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Buscar.setText("Buscar Pasajero");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, -1));

        Eliminar.setBackground(new java.awt.Color(153, 153, 255));
        Eliminar.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Eliminar.setText("Eliminar Pasajero");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, -1, -1));

        Infoi.setBackground(new java.awt.Color(204, 204, 0));
        Infoi.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Infoi.setText("Información Pasajeros del Vuelo");
        Infoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoiActionPerformed(evt);
            }
        });
        getContentPane().add(Infoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 730, -1, -1));

        b11.setBackground(new java.awt.Color(0, 255, 0));
        b11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b11.setText("11");
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        b10.setBackground(new java.awt.Color(0, 255, 0));
        b10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b10.setText("10");
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        b12.setBackground(new java.awt.Color(0, 255, 0));
        b12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b12.setText("12");
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        b13.setBackground(new java.awt.Color(0, 255, 0));
        b13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b13.setText("13");
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        b14.setBackground(new java.awt.Color(0, 255, 0));
        b14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b14.setText("14");
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        b9.setBackground(new java.awt.Color(0, 255, 0));
        b9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b9.setText("09");
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        b15.setBackground(new java.awt.Color(0, 255, 0));
        b15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b15.setText("15");
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        b16.setBackground(new java.awt.Color(0, 255, 0));
        b16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b16.setText("16");
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        b17.setBackground(new java.awt.Color(0, 255, 0));
        b17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b17.setText("17");
        getContentPane().add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        b18.setBackground(new java.awt.Color(0, 255, 0));
        b18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b18.setText("18");
        getContentPane().add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        b19.setBackground(new java.awt.Color(0, 255, 0));
        b19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b19.setText("19");
        getContentPane().add(b19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        b20.setBackground(new java.awt.Color(0, 255, 0));
        b20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b20.setText("20");
        getContentPane().add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        b21.setBackground(new java.awt.Color(0, 255, 0));
        b21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b21.setText("21");
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        b22.setBackground(new java.awt.Color(0, 255, 0));
        b22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b22.setText("22");
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        b23.setBackground(new java.awt.Color(0, 255, 0));
        b23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b23.setText("23");
        getContentPane().add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        b24.setBackground(new java.awt.Color(0, 255, 0));
        b24.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b24.setText("24");
        getContentPane().add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        b25.setBackground(new java.awt.Color(0, 255, 0));
        b25.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b25.setText("25");
        getContentPane().add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        b26.setBackground(new java.awt.Color(0, 255, 0));
        b26.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b26.setText("26");
        getContentPane().add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        b27.setBackground(new java.awt.Color(0, 255, 0));
        b27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b27.setText("27");
        getContentPane().add(b27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        b28.setBackground(new java.awt.Color(0, 255, 0));
        b28.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b28.setText("28");
        getContentPane().add(b28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        b29.setBackground(new java.awt.Color(0, 255, 0));
        b29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b29.setText("29");
        getContentPane().add(b29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        b30.setBackground(new java.awt.Color(0, 255, 0));
        b30.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b30.setText("30");
        getContentPane().add(b30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        b31.setBackground(new java.awt.Color(0, 255, 0));
        b31.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b31.setText("31");
        getContentPane().add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        b32.setBackground(new java.awt.Color(0, 255, 0));
        b32.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b32.setText("32");
        getContentPane().add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        b33.setBackground(new java.awt.Color(0, 255, 0));
        b33.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b33.setText("33");
        getContentPane().add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        b34.setBackground(new java.awt.Color(0, 255, 0));
        b34.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b34.setText("34");
        getContentPane().add(b34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        b35.setBackground(new java.awt.Color(0, 255, 0));
        b35.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b35.setText("35");
        getContentPane().add(b35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        b36.setBackground(new java.awt.Color(0, 255, 0));
        b36.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b36.setText("36");
        getContentPane().add(b36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        b37.setBackground(new java.awt.Color(0, 255, 0));
        b37.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b37.setText("37");
        getContentPane().add(b37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, -1, -1));

        b38.setBackground(new java.awt.Color(0, 255, 0));
        b38.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b38.setText("38");
        getContentPane().add(b38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, -1, -1));

        b39.setBackground(new java.awt.Color(0, 255, 0));
        b39.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b39.setText("39");
        getContentPane().add(b39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        b40.setBackground(new java.awt.Color(0, 255, 0));
        b40.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b40.setText("40");
        getContentPane().add(b40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        b41.setBackground(new java.awt.Color(0, 255, 0));
        b41.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b41.setText("41");
        getContentPane().add(b41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        b42.setBackground(new java.awt.Color(0, 255, 0));
        b42.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b42.setText("42");
        getContentPane().add(b42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        b43.setBackground(new java.awt.Color(0, 255, 0));
        b43.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b43.setText("43");
        getContentPane().add(b43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        b44.setBackground(new java.awt.Color(0, 255, 0));
        b44.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b44.setText("44");
        getContentPane().add(b44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        b45.setBackground(new java.awt.Color(0, 255, 0));
        b45.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b45.setText("45");
        getContentPane().add(b45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, -1, -1));

        b46.setBackground(new java.awt.Color(0, 255, 0));
        b46.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b46.setText("46");
        getContentPane().add(b46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        b47.setBackground(new java.awt.Color(0, 255, 0));
        b47.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b47.setText("47");
        getContentPane().add(b47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, -1, -1));

        b48.setBackground(new java.awt.Color(0, 255, 0));
        b48.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b48.setText("48");
        getContentPane().add(b48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        b49.setBackground(new java.awt.Color(0, 255, 0));
        b49.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b49.setText("49");
        getContentPane().add(b49, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        b50.setBackground(new java.awt.Color(0, 255, 0));
        b50.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b50.setText("50");
        getContentPane().add(b50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserva_vuelos/anchura.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 690, 780));

        progress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progress.setText("0%");
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibresActionPerformed

    private void RegistrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrariActionPerformed
        // TODO add your handling code here:
        Registrar r = new Registrar();
        r.setVisible(true);
    }//GEN-LAST:event_RegistrariActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        Buscar b = new Buscar();
        b.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        Eliminar e = new Eliminar();
        e.setVisible(true);
    }//GEN-LAST:event_EliminarActionPerformed

    private void InfoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoiActionPerformed
        // TODO add your handling code here:
        Info i = new Info();
        i.setVisible(true);
        //tabla info
        for (int e=0; e < Registrar.listaPasajeros.size(); e++) {
            
        Info.table[0] = Registrar.listaPasajeros.get(e).getNombre();
        Info.table[1] = Integer.toString(Registrar.listaPasajeros.get(e).getCedula());
        Info.table[2] = Integer.toString(Registrar.listaPasajeros.get(e).getPuesto());
        Info.table[3] = Registrar.listaPasajeros.get(e).getClase();
        Info.table[4] = Registrar.listaPasajeros.get(e).getUbicacion();

        Info.tabla1.addRow(Info.table);        
        //
        }
        
    }//GEN-LAST:event_InfoiActionPerformed

    private void OcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcupadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OcupadosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Libres.setText(Integer.toString(Sillas));
        Ocupados.setText(Integer.toString(Ocu));
                //
                sillasj.add(b1);
                sillasj.add(b4);
                sillasj.add(b5);
                sillasj.add(b8);
                sillasj.add(b2);
                sillasj.add(b3);
                sillasj.add(b6);
                sillasj.add(b7);
                //-[0,1,2,3,  4,5,6,7]-
                // [1,4,5,8,  2,3,6,7]
                //
                
                sillasc.add(b9);//0
                sillasc.add(b14);
                sillasc.add(b15);
                sillasc.add(b20);
                sillasc.add(b21);
                sillasc.add(b26);//5
                sillasc.add(b27);
                sillasc.add(b32);
                sillasc.add(b33);
                sillasc.add(b38);
                sillasc.add(b39);//10
                sillasc.add(b44);
                sillasc.add(b45);
                sillasc.add(b50);//13
                sillasc.add(b10);
                sillasc.add(b13);//15
                sillasc.add(b16);
                sillasc.add(b19);
                sillasc.add(b22);
                sillasc.add(b25);
                sillasc.add(b28);//20
                sillasc.add(b31);
                sillasc.add(b34);
                sillasc.add(b37);
                sillasc.add(b40);
                sillasc.add(b43);//25
                sillasc.add(b46);
                sillasc.add(b49);//27
                sillasc.add(b11);
                sillasc.add(b12);
                sillasc.add(b17);//30
                sillasc.add(b18);
                sillasc.add(b23);
                sillasc.add(b24);
                sillasc.add(b29);
                sillasc.add(b30);//35
                sillasc.add(b35);
                sillasc.add(b36);
                sillasc.add(b41);
                sillasc.add(b42);
                sillasc.add(b47);//40
                sillasc.add(b48);//41
                /*Ubicacion = 
               -[0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13]-
                [9,14,15,20,21,26,27,32,33,38,39,44,45,50,/Ventana  
                
               -[14,15,16,17,18,19,20,21,22,23,24,25,26,27]-
                 10,13,16,19,22,25,28,31,34,37,40,43,46,49,/Centro 
                
               -[28,29,30,31,32,33,34,35,36,37,38,39,40,41]- 
                 11,12,17,18,23,24,29,30,35,36,41,42,47,48/pasillo ]*/
                
                //sillas totales en orden
                sillast.add(b1);
                sillast.add(b2);
                sillast.add(b3);
                sillast.add(b4);
                sillast.add(b5);
                sillast.add(b6);
                sillast.add(b7);
                sillast.add(b8);
                sillast.add(b9);
                sillast.add(b10);
                sillast.add(b11);
                sillast.add(b12);
                sillast.add(b13);
                sillast.add(b14);
                sillast.add(b15);
                sillast.add(b16);
                sillast.add(b17);
                sillast.add(b18);
                sillast.add(b19);
                sillast.add(b20);
                sillast.add(b21);
                sillast.add(b22);
                sillast.add(b23);
                sillast.add(b24);
                sillast.add(b25);
                sillast.add(b26);
                sillast.add(b27);
                sillast.add(b28);
                sillast.add(b29);
                sillast.add(b30);
                sillast.add(b31);
                sillast.add(b32);
                sillast.add(b33);
                sillast.add(b34);
                sillast.add(b35);
                sillast.add(b36);
                sillast.add(b37);
                sillast.add(b38);
                sillast.add(b39);
                sillast.add(b40);
                sillast.add(b41);
                sillast.add(b42);
                sillast.add(b43);
                sillast.add(b44);
                sillast.add(b45);
                sillast.add(b46);
                sillast.add(b47);
                sillast.add(b48);
                sillast.add(b49);
                sillast.add(b50);
                
    }//GEN-LAST:event_formWindowOpened

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        //contadores estadisticas
        int contm = 0;
        int conth = 0;
        int conty = 0;
        int contx = 0;
        int sumedad = 0;
        int min = 150;
        int max = 0;
        //
        for(int i=0; i < Registrar.listaPasajeros.size(); i++) {
            //sexos
            if ( Registrar.listaPasajeros.get(i).getSexo().equals("Femenino") ) {
               //Masculino / Femenino
               contm += 1;
               Interfaz.mujeres.setText(Integer.toString(contm));
            }else if ( Registrar.listaPasajeros.get(i).getSexo().equals("Masculino") ) {
               //Masculino / Femenino
               conth += 1;
               Interfaz.hombres.setText(Integer.toString(conth));
            }
            //edades
            if ( Registrar.listaPasajeros.get(i).getEdad() >= 18 ) {
               conty += 1;
               Interfaz.mayores.setText(Integer.toString(conty));
            } else if ( Registrar.listaPasajeros.get(i).getEdad() < 18 ) {
               contx += 1;
               Interfaz.menores.setText(Integer.toString(contx));
            }
            //promedio edad
            sumedad += Registrar.listaPasajeros.get(i).getEdad();
            int tam = Registrar.listaPasajeros.size();
            
            Interfaz.promEdad.setText(Integer.toString( sumedad / tam ));
            //mas joven
            if (Registrar.listaPasajeros.get(i).getEdad() < min) {
                min = Registrar.listaPasajeros.get(i).getEdad();
                Interfaz.joven.setText(Registrar.listaPasajeros.get(i).
                getNombre() + " , " + Integer.toString(min));
            }
            //mas viejo
            if (Registrar.listaPasajeros.get(i).getEdad() > max) {
                max = Registrar.listaPasajeros.get(i).getEdad();
                Interfaz.viejo.setText(Registrar.listaPasajeros.get(i).
                getNombre() + " , " + Integer.toString(max));
            }
            
        }//ciclo
       //boton
    }//GEN-LAST:event_ReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    public static int Sillas = 50;
    public static int Ocu = 0;
    //
    public static ArrayList<javax.swing.JButton> sillasj = new ArrayList<javax.swing.JButton>();
    public static ArrayList<javax.swing.JButton> sillasc = new ArrayList<javax.swing.JButton>();
    public static ArrayList<javax.swing.JButton> sillast = new ArrayList<javax.swing.JButton>();
    //
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Infoi;
    public static javax.swing.JTextField Libres;
    public static javax.swing.JTextField Ocupados;
    private javax.swing.JButton Registrari;
    private javax.swing.JButton Reload;
    public static javax.swing.JButton b1;
    public static javax.swing.JButton b10;
    public static javax.swing.JButton b11;
    public static javax.swing.JButton b12;
    public static javax.swing.JButton b13;
    public static javax.swing.JButton b14;
    public static javax.swing.JButton b15;
    public static javax.swing.JButton b16;
    public static javax.swing.JButton b17;
    public static javax.swing.JButton b18;
    public static javax.swing.JButton b19;
    public static javax.swing.JButton b2;
    public static javax.swing.JButton b20;
    public static javax.swing.JButton b21;
    public static javax.swing.JButton b22;
    public static javax.swing.JButton b23;
    public static javax.swing.JButton b24;
    public static javax.swing.JButton b25;
    public static javax.swing.JButton b26;
    public static javax.swing.JButton b27;
    public static javax.swing.JButton b28;
    public static javax.swing.JButton b29;
    public static javax.swing.JButton b3;
    public static javax.swing.JButton b30;
    public static javax.swing.JButton b31;
    public static javax.swing.JButton b32;
    public static javax.swing.JButton b33;
    public static javax.swing.JButton b34;
    public static javax.swing.JButton b35;
    public static javax.swing.JButton b36;
    public static javax.swing.JButton b37;
    public static javax.swing.JButton b38;
    public static javax.swing.JButton b39;
    public static javax.swing.JButton b4;
    public static javax.swing.JButton b40;
    public static javax.swing.JButton b41;
    public static javax.swing.JButton b42;
    public static javax.swing.JButton b43;
    public static javax.swing.JButton b44;
    public static javax.swing.JButton b45;
    public static javax.swing.JButton b46;
    public static javax.swing.JButton b47;
    public static javax.swing.JButton b48;
    public static javax.swing.JButton b49;
    public static javax.swing.JButton b5;
    public static javax.swing.JButton b50;
    public static javax.swing.JButton b6;
    public static javax.swing.JButton b7;
    public static javax.swing.JButton b8;
    public static javax.swing.JButton b9;
    public static javax.swing.JTextField hombres;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField joven;
    public static javax.swing.JTextField mayores;
    public static javax.swing.JTextField menores;
    public static javax.swing.JTextField mujeres;
    public static javax.swing.JProgressBar progreso;
    public static javax.swing.JLabel progress;
    public static javax.swing.JTextField promEdad;
    public static javax.swing.JTextField viejo;
    // End of variables declaration//GEN-END:variables
}
