/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva_vuelos;

import static java.awt.Color.red;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Registrar extends javax.swing.JFrame {
    
    public static ArrayList<Pasajero> listaPasajeros = new ArrayList<>();
    public static ArrayList<Integer> listaCedulas = new ArrayList<>();
    
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        cedular = new javax.swing.JTextField();
        nombrer = new javax.swing.JTextField();
        edadr = new javax.swing.JTextField();
        sexor = new javax.swing.JComboBox<>();
        claser = new javax.swing.JComboBox<>();
        ubir = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cédula:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Edad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Clase:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ubicación:");

        Registrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        sexor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        claser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejecutiva", "Economica" }));
        claser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claserActionPerformed(evt);
            }
        });

        ubir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventana", "Pasillo" }));
        ubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(cedular, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ubir, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(claser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sexor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edadr)
                                    .addComponent(nombrer)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Registrar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sexor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(claser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addComponent(Registrar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
        try {
            if ( listaCedulas.contains(Integer.parseInt(cedular.getText() ) ) ) {
                javax.swing.JOptionPane.showMessageDialog(null,
                "La cédula que con la que se desea registrar ya ha sido ocupada anteriormente.",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }else {
                //
                int cedula = Integer.parseInt(cedular.getText());
                String nombre = nombrer.getText();
                int edad = Integer.parseInt(edadr.getText());
                String sexo = sexor.getSelectedItem().toString();
                String clase = claser.getSelectedItem().toString();
                String ubicacion = ubir.getSelectedItem().toString();
                int puesto = 0;
                //
            if ( clase.equals("Ejecutiva") && ubicacion.equals("Ventana") && Interfaz.sillasj.get(3).getBackground() == red ){
                javax.swing.JOptionPane.showMessageDialog(null,
                "Los Asientos con la clase y ubicacion deseadas se encuentran "
                + "ocupados, cambie su eleccion o intentelo mas tarde. ",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }
            else if ( clase.equals("Ejecutiva") && ubicacion.equals("Pasillo") && Interfaz.sillasj.get(7).getBackground() == red ){
                javax.swing.JOptionPane.showMessageDialog(null,
                "Los Asientos con la clase y ubicacion deseadas se encuentran "
                + "ocupados, cambie su eleccion o intentelo mas tarde. ",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }
            else if ( clase.equals("Economica") && ubicacion.equals("Ventana") && Interfaz.sillasc.get(13).getBackground() == red ){
                javax.swing.JOptionPane.showMessageDialog(null,
                "Los Asientos con la clase y ubicacion deseadas se encuentran "
                + "ocupados, cambie su eleccion o intentelo mas tarde. ",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }
            else if ( clase.equals("Economica") && ubicacion.equals("Centro") && Interfaz.sillasc.get(27).getBackground() == red ){
                javax.swing.JOptionPane.showMessageDialog(null,
                "Los Asientos con la clase y ubicacion deseadas se encuentran "
                + "ocupados, cambie su eleccion o intentelo mas tarde. ",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }
            else if ( clase.equals("Economica") && ubicacion.equals("Pasillo") && Interfaz.sillasc.get(41).getBackground() == red ){
                javax.swing.JOptionPane.showMessageDialog(null,
                "Los Asientos con la clase y ubicacion deseadas se encuentran "
                + "ocupados, cambie su eleccion o intentelo mas tarde. ",
                "Error al Registrar",JOptionPane.WARNING_MESSAGE);
            }
            else {//
            //
            Interfaz.Sillas -= 1;
            Interfaz.Ocu += 1;

            Interfaz.Libres.setText(Integer.toString(Interfaz.Sillas));
            Interfaz.Ocupados.setText(Integer.toString(Interfaz.Ocu));
            
            Interfaz.progreso.setValue(Interfaz.Ocu);
            Interfaz.progress.setText(Integer.toString(Interfaz.Ocu * 2) + "%");
            //

            if ( clase.equals("Ejecutiva") ) {

                switch ( ubicacion ) {
                    case "Ventana":
                        for (int i = 0; i < 4; i++) {
                            if (Interfaz.sillasj.get(i).getBackground() != red) {
                                Interfaz.sillasj.get(i).setBackground(red);
                                puesto = Integer.parseInt(Interfaz.sillasj.get(i).getText());
                                break;
                            }
                        }
                        break;
                    case "Pasillo":
                        for (int i = 4; i < 8; i++) {
                            if (Interfaz.sillasj.get(i).getBackground() != red) {
                                Interfaz.sillasj.get(i).setBackground(red);
                                puesto = Integer.parseInt(Interfaz.sillasj.get(i).getText());
                                break;
                            }	
                        }
                        break;
                }
            //
            }else if (clase.equals("Economica")) {

                switch ( ubicacion ) {
                    case "Ventana":
                        for (int i = 0; i < 14; i++) {
                            if (Interfaz.sillasc.get(i).getBackground() != red) {
                                Interfaz.sillasc.get(i).setBackground(red);
                                puesto = Integer.parseInt(Interfaz.sillasc.get(i).getText());
                                break;
                            }
                        }
                        break;
                    case "Centro":
                        for (int i = 14; i < 28; i++) {
                            if (Interfaz.sillasc.get(i).getBackground() != red) {
                                Interfaz.sillasc.get(i).setBackground(red);
                                puesto = Integer.parseInt(Interfaz.sillasc.get(i).getText());
                                break;
                            }	
                        }
                        break;
                    case "Pasillo":
                        for (int i = 28; i < 42; i++) {
                            if (Interfaz.sillasc.get(i).getBackground() != red) {
                                Interfaz.sillasc.get(i).setBackground(red);
                                puesto = Integer.parseInt(Interfaz.sillasc.get(i).getText());
                                break;
                            }	
                        }
                        break;
                }
            }//
            
            //
            Pasajero p1 = new Pasajero(cedula,nombre,edad,sexo,clase,ubicacion,puesto);
            listaPasajeros.add(p1);
            listaCedulas.add( p1.getCedula() );
            //
            
            //
            cedular.setText("");
            nombrer.setText("");
            edadr.setText("");
            
            javax.swing.JOptionPane.showMessageDialog(null,"El pasajero se ha registrado exitosamente",
            "Registo Exitoso",JOptionPane.INFORMATION_MESSAGE);
            //
            }//ocupados
            }//else
        }catch (Exception ex){
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "Debe llenar todos los espacios con el tipo de dato indicado",
                        "Error al ingresar los datos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void claserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claserActionPerformed
        // TODO add your handling code here:
        if (claser.getSelectedIndex() == 1){
            ubir.addItem("Centro");
        } 
        if (claser.getSelectedIndex() == 0){
            ubir.removeItemAt(2);
        }
    }//GEN-LAST:event_claserActionPerformed

    private void ubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
                
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    public static javax.swing.JTextField cedular;
    public static javax.swing.JComboBox<String> claser;
    public static javax.swing.JTextField edadr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField nombrer;
    public static javax.swing.JComboBox<String> sexor;
    public static javax.swing.JComboBox<String> ubir;
    // End of variables declaration//GEN-END:variables

    private int getSelectedIndex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
