/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matriculas;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Interfaz extends javax.swing.JFrame {
    
    public static ArrayList<String> listaNombres = new ArrayList<>();

    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
	}catch (NumberFormatException nfe){
            return false;
	}
    }

    /**
     * Creates new form 
     */
    public Interfaz() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pcombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ecombo = new javax.swing.JComboBox<>();
        bRegistrar = new javax.swing.JButton();
        bEstd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        costoText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        porcentajeText = new javax.swing.JTextField();
        DineroText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnica en Mercadeo", "Tecnica en Informatica", "Tecnica en Contabilidad" }));
        pcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcomboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Programa:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del estudiante:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Estrato:");

        ecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        ecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecomboActionPerformed(evt);
            }
        });

        bRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRegistrar.setText("Matricular");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        bEstd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEstd.setText("Estadísticas");
        bEstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Costo del Programa Escodigo:");

        costoText.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Costo con el descuento aplicado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Descuento en Porcentaje:");

        porcentajeText.setEditable(false);

        DineroText.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bRegistrar)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(bEstd)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pcombo, 0, 218, Short.MAX_VALUE)
                            .addComponent(nombreText)
                            .addComponent(ecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(costoText)
                            .addComponent(porcentajeText)
                            .addComponent(DineroText))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(costoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(porcentajeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DineroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEstd)
                    .addComponent(bRegistrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcomboActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            //
            Interfaz.cont += 1;

            String prg = pcombo.getSelectedItem().toString();
            String name = nombreText.getText();
            int num = 0;
            int strt = Integer.parseInt( ecombo.getSelectedItem().toString() );
            //
            if ( listaNombres.contains(name) || Interfaz.isNumeric(name) || name.isEmpty()) {
                
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "Debe llenar todos los espacios con el tipo de dato "
                        + "indicado, puede haber indicado un nombre ya registrado",
                        "Error al ingresar los datos",JOptionPane.ERROR_MESSAGE);
                
            }else {
                
                switch (prg) {
                    case "Tecnica en Mercadeo":
                        programa ob1 = new programa(name, 1000, num, strt);
                        ob1.matricular();
                        listaNombres.add(ob1.getNombre());
                        if ( strt == 1 || strt == 2 || strt == 3 ){
                            ob1.setValor(1000 - 1000 * 0.232);
                            porcentajeText.setText("23.2%");
                        }else if (strt == 4 || strt == 5){
                            ob1.setValor(1000 - 1000 * 0.132);
                            porcentajeText.setText("13.2%");
                        }else {
                            porcentajeText.setText("No aplica");
                        }
                        costoText.setText( Integer.toString(1000) );
                        DineroText.setText(Double.toString( ob1.getValor() ));
                        //costoText.setText( Integer.toString( ob1.getNum() ) );
                        break;
                    case "Tecnica en Informatica":
                        programa ob2 = new programa(name, 1000, num, strt);
                        ob2.matricular();
                        listaNombres.add(ob2.getNombre());
                        if ( strt == 1 || strt == 2 || strt == 3 ){
                            ob2.setValor(1000 - 1000 * 0.232);
                            porcentajeText.setText("23.2%");
                        }else if (strt == 4 || strt == 5){
                            ob2.setValor(1000 - 1000 * 0.132);
                            porcentajeText.setText("13.2%");
                        }else {
                            porcentajeText.setText("No aplica");
                        }
                        costoText.setText( Integer.toString(1000) );
                        DineroText.setText(Double.toString( ob2.getValor() ));
                        break;
                    case "Tecnica en Contabilidad":
                        programa ob3 = new programa(name, 1200, num, strt);
                        ob3.matricular();
                        listaNombres.add(ob3.getNombre());
                        if ( strt == 1 || strt == 2 || strt == 3 ){
                            ob3.setValor(1200 - 1200 * 0.232);
                            porcentajeText.setText("23.2%");
                        }else if (strt == 4 || strt == 5){
                            ob3.setValor(1200 - 1200 * 0.132);
                            porcentajeText.setText("13.2%");
                        }else {
                            porcentajeText.setText("No aplica");
                        }
                        costoText.setText( Integer.toString(1200) );
                        DineroText.setText(Double.toString( ob3.getValor() ));
                        porcentajeText.setText("");
                        break;
                }
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "El estudiante se ha matriculado con exito!",
                        "Registo satisfactorio",JOptionPane.INFORMATION_MESSAGE);
                
            }
        }catch (Exception ex){
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "Debe llenar todos los espacios con el tipo de dato indicado",
                        "Error al ingresar los datos",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void ecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecomboActionPerformed

    private void bEstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstdActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, 
                        "No me dio el tiempo para haer las estadisticas",
                        "Profe perdon :(",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bEstdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    public static int cont = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DineroText;
    public static javax.swing.JButton bEstd;
    public static javax.swing.JButton bRegistrar;
    private javax.swing.JTextField costoText;
    public static javax.swing.JComboBox<String> ecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField nombreText;
    public static javax.swing.JComboBox<String> pcombo;
    private javax.swing.JTextField porcentajeText;
    // End of variables declaration//GEN-END:variables
}
